# Generated by Django 3.1 on 2021-06-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0004_auto_20210625_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
    ]
