# Generated by Django 3.1 on 2021-06-28 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0007_profile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
    ]
